export const actionTypes = {
    FETCH_ARTWORKS_BY_PAGE_REQUEST: 'FETCH_ARTWORKS_BY_PAGE_REQUEST',
    FETCH_ARTWORKS_BY_PAGE_SUCCESS: 'FETCH_ARTWORKS_BY_PAGE_SUCCESS',
    FETCH_ARTWORKS_BY_PAGE_FAIL: 'FETCH_ARTWORKS_BY_PAGE_FAIL',

    FETCH_SELECTED_ARTWORK_REQUEST: 'FETCH_SELECTED_ARTWORK_REQUEST',
    FETCH_SELECTED_ARTWORK_SUCCESS: 'FETCH_SELECTED_ARTWORK_SUCCESS',
    FETCH_SELECTED_ARTWORK_FAIL: 'FETCH_SELECTED_ARTWORK_FAIL',
    REMOVE_SELECTED_ARTWORK: 'REMOVE_SELECTED_ARTWORK',

    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',

    SEARCH_BY_QUERY_REQUEST: 'SEARCH_BY_QUERY_REQUEST',
    SEARCH_BY_QUERY_SUCCESS: 'SEARCH_BY_QUERY_SUCCESS',
    SEARCH_BY_QUERY_FAIL: 'SEARCH_BY_QUERY_FAIL',
    REMOVE_SEARCH_RESULTS: 'REMOVE_SEARCH_RESULTS'
}