export const actionTypes = {
    FETCH_ARTWORKS_BY_PAGE_SUCCESS: 'FETCH_ARTWORKS_BY_PAGE_SUCCESS',
    FETCH_ARTWORKS_BY_PAGE_FAIL: 'FETCH_ARTWORKS_BY_PAGE_FAIL',

    FETCH_SELECTED_ARTWORK: 'FETCH_SELECTED_ARTWORK',
    REMOVE_SELECTED_ARTWORK: 'REMOVE_SELECTED_ARTWORK',
}