export const actionTypes = {
    FETCH_ARTWORKS_BY_PAGE_SUCCESS: 'FETCH_ARTWORKS_BY_PAGE_SUCCESS',
    FETCH_ARTWORKS_BY_PAGE_FAIL: 'FETCH_ARTWORKS_BY_PAGE_FAIL',

    FETCH_SELECTED_ARTWORK: 'FETCH_SELECTED_ARTWORK',
    REMOVE_SELECTED_ARTWORK: 'REMOVE_SELECTED_ARTWORK',

    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',

    SEARCH_BY_QUERY: 'SEARCH_BY_QUERY',
    REMOVE_SEARCH_RESULTS: 'REMOVE_SEARCH_RESULTS'
}